### ISSUE TITLE
M-10. Необходимо устранить ошибки и предупреждения, выдаваемые W3C валидатором.

### ISSUE THREAD

**Issue by shadow-reviewer** [dev-mathematics-by/dev-mathematics-by.github.io#10]
Пример для главной страницы:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmathematics.by%2F

Данный EPIC был в результате разбит на три issues:
[M-41](https://github.com/dev-mathematics-by/dev-mathematics-by.github.io/issues/41)
[M-64](https://github.com/dev-mathematics-by/dev-mathematics-by.github.io/issues/64)
[M-70](https://github.com/dev-mathematics-by/dev-mathematics-by.github.io/issues/70)

**Comment by dev-mathematics-by** [comment]
@ValentinaBondarenko, вы пофиксили alt для img - устраняйте остальные, ошибки.
Issues для остальных ошибок создайте на свое усмотрение:
- либо одно для всех оставшихся ошибок;
- либо - на каждую ошибку
- либо - на связанную группу ошибок - я бы предпочел это.

**Comment by dev-mathematics-by** [comment]
![image](https://user-images.githubusercontent.com/74928091/107319717-6c60be80-6ab0-11eb-95f5-8fa04d6d157b.png)
Ok.
