### ISSUE TITLE
Исправить ошибки и форматирования css кода на странице index.html

### ISSUE THREAD

**Issue by ValentinaBondarenko** [dev-mathematics-by/dev-mathematics-by.github.io#42]
### Перечень
1.  две ошибки.
2. отступы для media-screen (форматирование)
3. расположение фигурных скобок (форматирование)
**Note**:  2 отдельных коммита

**Comment by ValentinaBondarenko** [comment]
@dev-mathematics-by
 Предлагаю включить это в первый релиз!

**Comment by dev-mathematics-by** [comment]
@ValentinaBondarenko - согласен.
